### ISSUE TITLE
Connection Error

### ISSUE THREAD

**Issue by matcha6666** [EchterAlsFake/Porn_Fetch#4] opened 2023-09-03 12:19 UTC
Appea mistaker，requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))

**Comment by EchterAlsFake** [comment] 2023-09-03 16:11
Hey,

thanks for reporting the error.


I already know about the connection Error, but I can not do anything about it. The problem is with PornHub itself and not with my Application.

The author of the API is working on an update, where he tries to optimize some things, also with the cache stuff to load the content in a better way. I hope that the API update will fix the connection error, but for now I can't do anything.

Just in case you've disabled the delay, you need to enable it.  

I leave this open, so that others don't report it for a second time

Have a nice day :)

**Comment by matcha6666** [comment] 2023-09-17 11:12
hi,
appear attributeerror: module 'phub.utils' has no attribute 'remove_video_ads'How to solve

**Comment by EchterAlsFake** [comment] 2023-09-17 14:12
Hey, 

I was not able to reproduce your error. Please give me some additional information:

- The video url
- The version you are using

Thanks :)

**Comment by matcha6666** [comment] 2023-09-17 14:19
edition：Porn_Fetch_2.6
website：https://cn.pornhub.com/model/nobuaki_sekioka
Add model/channel,url, 
appear attributeerror: module 'phub.utils' has no attribute 'remove_video_ads'

**Comment by EchterAlsFake** [comment] 2023-09-17 14:35
Thanks for the additional information.

I got it now.

The problem is with the API, I opened an Issue about this on PHUB. I let you know when it's fixed :)

**Comment by EchterAlsFake** [comment] 2023-09-17 16:51
Okay, So it is a little bit complicated.

PornHub changed some stuff and that's why some things from the API don't work anymore.
There's a fix for it, but if I apply that fix other things are gonna be breaking. 

So you need to live with it. Sorry.

**Comment by matcha6666** [comment] 2023-09-17 16:54
ok,I hope you can solve it perfectly

**Comment by EchterAlsFake** [comment] 2023-09-21 17:29
Fixed with Release 2.7 :)

**Comment by matcha6666** [comment] 2023-09-21 18:02
> 在 2.7 版:)中修复

Your repair is perfect. When I used it, I found that the videos retrieved by Add model/channel were not complete enough. For example, the model had 69 videos, and only 61 were retrieved for download. How to retrieve all the videos can be added. Go to the download bar
版本：Porn_Fetch_2.7
网站：https://cn.pornhub.com/model/ada-kham

**Comment by EchterAlsFake** [comment] 2023-09-22 09:35
Hi, 

This is due to an Index Error. I don't know why it happens, because it happens only on some videos. I am reporting this Issue to the API Developer and hopefully he can fix this Issue. I reopen this issue now and I tell you when it's fixed.

Have an awesome day :)

**Comment by EchterAlsFake** [comment] 2023-09-22 15:36
Fixed with newest 2.7 binaries :) 

(Just for the future, If you get other issues, please report them in a new thread and not under this one)

**Closed by EchterAlsFake** 2023-09-22 15:36 UTC
