### ISSUE TITLE
Error installing in Windows

### ISSUE THREAD

**Issue by RalfEs73** [EchterAlsFake/Porn_Fetch#60] opened 2024-11-16 17:07 UTC
When using the installation script in Powershell you get an error message:

`INFO:root:[DEPLOY] Deployment directory purged
INFO:root:[DEPLOY] End
Cleaning up...
Remove-Item:
Line |
  89 |  Remove-Item -Recurse -Force -Path (Join-Path $downloadsDir "Porn_Fetc …
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot remove the item at 'C:\Users\USER\AppData\Local\Temp\Porn_Fetch-master' because it is in use.
Done!
(venv) PS C:\Users\USER\AppData\Local\Temp\Porn_Fetch-master>`

**Comment by EchterAlsFake** [comment] 2024-11-16 19:33
Hi, the issue that you reported should be fixed now, but as I fixed it I recognized that the build scripts are not working as intended. At least not the Windows version and I need to do some fixing and testing. Although it has nothing to do with this issue itself, I'll still leave it open and close it when everything is fixed.

Just a quick reminder, that I wouldn't recommend self-compiling, because the master branch might be unstable as I am directly comitting every change on it. Sometimes I synchronize code from my Laptop to my PC and that might be unfinished code which causes the program to crash.

But if you want to do it anyways, I won't stop you xD


So thanks for reporting, have a nice day :)

**Comment by EchterAlsFake** [comment] 2024-11-16 21:53
Hi again, 

So I fixed the windows build script. I also need to adjust the MacOS and Linux ones, but for your case it should all be good now (hopefully). If you could test it and let me know I would be very happy. 

Thanks again for your time :)

**Closed** 2024-12-27 10:53 UTC
